__title__ = 'cleoslots'
__description__ = 'App for simulating sessions on the Cleopatra slot machine (1-line or 20-lines)'
__url__ = 'https://www.github.com/benmayersohn'
__version__ = '0.0.1'
__author__ = 'Ben Mayersohn'
__author_email__ = 'contact@benmayersohn.com'
__copyright__ = 'Copyright 2019 Ben Mayersohn'